local b='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
function GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO(data) m=string.sub(data, 0, 55) data=data:gsub(m,'')

data = string.gsub(data, '[^'..b..'=]', '') return (data:gsub('.', function(x) if (x == '=') then return '' end local r,f='',(b:find(x)-1) for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and '1' or '0') end return r; end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(x) if (#x ~= 8) then return '' end local c=0 for i=1,8 do c=c+(x:sub(i,i)=='1' and 2^(8-i) or 0) end return string.char(c) end)) end


 


-- TamperProtection.lua
-- Advanced anti-tamper module for Next-Gen Anti-Gift
-- Author: Deeps-x (expanded)
-- Purpose: Monitor GUI, critical functions/variables and remote hooks for tampering.

local Players = game:GetService(GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('kTlPyQuVNRjcyLNyxXVLKOhTrtDvuvXcvhhmjrMGjhJieFrJEMyVYpTUGxheWVycw=='))
local RunService = game:GetService(GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('vTjmHwmURHFshMVzknzHDauSkvcjsTbfBfPbNtGJweNXeIpYBuBsbFOUnVuU2VydmljZQ=='))
local LocalPlayer = Players.LocalPlayer

local TamperProtection = {}
TamperProtection.__index = TamperProtection

-- Public event fired when tamper detected
TamperProtection.OnTamperDetected = Instance.new(GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('SFDGlLUAdenvBpjPIhGCwceVJfbWosGyWQgXyuwtxBofMHEeZaNJTflQmluZGFibGVFdmVudA=='))

-- Internal state
local config = {
    CheckInterval = 3,        -- seconds between integrity checks
    AutoKick = true,          -- automatically kick on severe tamper
    KickMessage = GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('mBkrWmwyMOwazwpQhoZZMaytvHMwjTMZnafPQDvECsKmYGHiwfLPDUP8J+aqCBBbnRpLVNjYW06IFRhbXBlcmluZyBkZXRlY3RlZC4gQ2xpZW50IHN0b3BwZWQgdG8gcHJvdGVjdCB5b3VyIGFjY291bnQu'),
    RestoreIfRemoved = true, -- try to reparent/restore GUI if it was removed
    ReapplyHooks = true,     -- try to call RemoteGuard.ReapplyHooks() when available
}

local protectedInstances = {}   -- { name = instance }
local protectedFunctions = {}   -- { name = {ref = function, signature = string} }
local snapshots = {}
local running = false
local loops = {}

-- Optional linked modules (set by Main.lua when available)
TamperProtection.Logger = nil
TamperProtection.GUIManager = nil
TamperProtection.RemoteGuard = nil
TamperProtection.InventoryLock = nil
TamperProtection.Config = nil

-- Helpers -------------------------------------------------
local function safeCall(fn, ...)
    local s, r = pcall(fn, ...)
    if not s then
        -- ignore errors
    end
    return s, r
end

local function getInstancePath(inst)
    if not inst or not inst.Parent then
        return GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('RDSrDQSuFXzKPuNFESpmaEkUwmVdvWMcYxlCGnEjrCNrYfVbTrRHGClPG9ycGhhbj4=')
    end
    local parts = {}
    local current = inst
    for i=1,100 do
        if not current then break end
        table.insert(parts, 1, current.Name)
        if current == game then break end
        current = current.Parent
    end
    return table.concat(parts, GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('kJSLfeHSPpPlqBMRRJmTdADBrmOxrzIwQNSdvVEBvjIvnQFYrGuFyCXLg=='))
end

local function functionSignature(fn)
    -- best-effort fingerprint of a Lua function: tostring + debug info when available
    local sig = tostring(fn)
    local ok, info = pcall(function() return debug and debug.getinfo and debug.getinfo(fn) end)
    if ok and info then
        sig = sig .. GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('vFhHcTRMHURmEthkCZktzsRVKlQZsirUQJXcpvRPyACHwJdSbZTzydgfA==') .. (info.what or GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('iwSAXmkEzUMrKwsVwphmsZrHTJaKJLBcrmhurmPxjumQFQHmCoOIPebPw==')) .. GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('UWSyzxbZkzTOrfogGgHTLmEeryEetVKzDebnxiENmxwJguCMRTFEcxiOg==') .. (info.nups or 0)
    end
    return sig
end

local function log(msg, level)
    level = level or GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('GFwjCAScMeXURPnnkKvTwQDMfASZcGvjIfCfwSNeTrBpAfuWGPHZtHBaW5mbw==')
    if TamperProtection.Logger and TamperProtection.Logger.AddEntry then
        safeCall(function() TamperProtection.Logger:AddEntry(msg, level) end)
    else
        -- fallback: print when developer console is open (kept minimal)
        -- donGpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('pWpcjrldLcVrmmCiBsYMxyniymppjuQJELZXTDpqkCgFTOPFGhiLBeadCBzcGFtIG91dHB1dDsgb25seSBwcmludCBvbiBlcnJvcnMNCiAgICAgICAgaWYgbGV2ZWwgPT0g')errorGpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('jzGXCRStRUBMliXOcaUBIZEcNBnrjDrIlZhAgQrMfCfjtpWEIDBguxSIG9yIGxldmVsID09IA==')alertGpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('HzLxtgSTXxoYtBPElpqMvSwnGUXDiqFJlLImPGztRhkDnmnuUJhpoBBIHRoZW4NCiAgICAgICAgICAgIHBjYWxsKGZ1bmN0aW9uKCkgcHJpbnQo')[TamperProtection] GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('uaFzHaltAFMMkfzsLkHInYEECICmyKsesEkPMADptULQXWsRXcJaCDdLCBtc2cpIGVuZCkNCiAgICAgICAgZW5kDQogICAgZW5kDQplbmQNCg0KLS0gQ29yZSBwcm90ZWN0aW9uIGFjdGlvbnMgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQpsb2NhbCBmdW5jdGlvbiB0cmlnZ2VyVGFtcGVyKHJlYXNvbikNCiAgICBsb2co')Tamper detected: GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('tNIMBrlyYhMowKwDbdzcvJPtRAWcUxqAxEASOfaljHMJuSHttiONTbvIC4uIHRvc3RyaW5nKHJlYXNvbiksIA==')alertGpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('oPIDfrSeHCMDAjwgQJGtgAFMKHpnlbIwgIQfOtbDAoiBREExAeuvzMhKQ0KICAgIFRhbXBlclByb3RlY3Rpb24uT25UYW1wZXJEZXRlY3RlZDpGaXJlKHJlYXNvbikNCg0KICAgIC0tIHVwZGF0ZSBHVUkgc3RhdHVzDQogICAgaWYgVGFtcGVyUHJvdGVjdGlvbi5HVUlNYW5hZ2VyIGFuZCBUYW1wZXJQcm90ZWN0aW9uLkdVSU1hbmFnZXIuU2V0U3RhdHVzIHRoZW4NCiAgICAgICAgc2FmZUNhbGwoZnVuY3Rpb24oKSBUYW1wZXJQcm90ZWN0aW9uLkdVSU1hbmFnZXI6U2V0U3RhdHVzKA==')bypassGpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('egfrmoJazGQfBuqkoRRntICifVmJHMcRZqxikbwuTPCqapcqETnuDFVKSBlbmQpDQogICAgZW5kDQoNCiAgICAtLSBsb2NrIGludmVudG9yeSBpbW1lZGlhdGVseQ0KICAgIGlmIFRhbXBlclByb3RlY3Rpb24uSW52ZW50b3J5TG9jayBhbmQgVGFtcGVyUHJvdGVjdGlvbi5JbnZlbnRvcnlMb2NrLkxvY2tJbnZlbnRvcnkgdGhlbg0KICAgICAgICBzYWZlQ2FsbChmdW5jdGlvbigpIFRhbXBlclByb3RlY3Rpb24uSW52ZW50b3J5TG9jazpMb2NrSW52ZW50b3J5KCkgZW5kKQ0KICAgIGVuZA0KDQogICAgLS0gYXR0ZW1wdCB0byByZWFwcGx5IGhvb2tzIGlmIGFwcGxpY2FibGUNCiAgICBpZiBjb25maWcuUmVhcHBseUhvb2tzIGFuZCBUYW1wZXJQcm90ZWN0aW9uLlJlbW90ZUd1YXJkIGFuZCBUYW1wZXJQcm90ZWN0aW9uLlJlbW90ZUd1YXJkLlJlYXBwbHlIb29rcyB0aGVuDQogICAgICAgIHNhZmVDYWxsKGZ1bmN0aW9uKCkgVGFtcGVyUHJvdGVjdGlvbi5SZW1vdGVHdWFyZDpSZWFwcGx5SG9va3MoKSBlbmQpDQogICAgZW5kDQoNCiAgICAtLSBvcHRpb25hbGx5IGF0dGVtcHQgdG8gcmVzdG9yZSBHVUkNCiAgICBpZiBjb25maWcuUmVzdG9yZUlmUmVtb3ZlZCBhbmQgVGFtcGVyUHJvdGVjdGlvbi5HVUlNYW5hZ2VyIGFuZCBUYW1wZXJQcm90ZWN0aW9uLkdVSU1hbmFnZXIuU2NyZWVuR3VpIHRoZW4NCiAgICAgICAgbG9jYWwgc2cgPSBUYW1wZXJQcm90ZWN0aW9uLkdVSU1hbmFnZXIuU2NyZWVuR3VpDQogICAgICAgIGlmIG5vdCBzZy5QYXJlbnQgdGhlbg0KICAgICAgICAgICAgcGNhbGwoZnVuY3Rpb24oKQ0KICAgICAgICAgICAgICAgIC0tIHRyeSB0byByZXBhcmVudCB0byBQbGF5ZXJHdWkNCiAgICAgICAgICAgICAgICBzZy5QYXJlbnQgPSBMb2NhbFBsYXllcjpGaW5kRmlyc3RDaGlsZCg=')PlayerGuiGpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('unsPBBioigjLljpOZDmAqRSZbRMZubsTOgHjOqBQbKrLslkMZCiSNIOKSBvciBMb2NhbFBsYXllcg0KICAgICAgICAgICAgZW5kKQ0KICAgICAgICBlbmQNCiAgICBlbmQNCg0KICAgIC0tIGlmIGNvbmZpZ3VyZWQsIGtpY2sgdGhlIGNsaWVudCBmb3IgcHJvdGVjdGlvbg0KICAgIGlmIGNvbmZpZy5BdXRvS2ljayB0aGVuDQogICAgICAgIHBjYWxsKGZ1bmN0aW9uKCkgTG9jYWxQbGF5ZXI6S2ljayhjb25maWcuS2lja01lc3NhZ2UpIGVuZCkNCiAgICBlbmQNCmVuZA0KDQotLSBJbnRlZ3JpdHkgY2hlY2tzIC0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLQ0KbG9jYWwgZnVuY3Rpb24gY2hlY2tJbnN0YW5jZXMoKQ0KICAgIGZvciBuYW1lLCBpbnN0IGluIHBhaXJzKHByb3RlY3RlZEluc3RhbmNlcykgZG8NCiAgICAgICAgaWYgbm90IGluc3Qgb3Igbm90IGluc3QuUGFyZW50IHRoZW4NCiAgICAgICAgICAgIHRyaWdnZXJUYW1wZXIo')Protected instance removed or parenting changed: GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('UQXpDhPXyohzwbioCdrfvkPjDiDAZAuCMxwELpxageMVqxOnsnnkJPNIC4uIHRvc3RyaW5nKG5hbWUpIC4uIA==') path:GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('IVFdINcrSQrTXrwEPIkfOqtKatBPbylIKXZCKETpDIEcfErMWvOzsQgIC4uIGdldEluc3RhbmNlUGF0aChpbnN0KSkNCiAgICAgICAgICAgIHJldHVybiB0cnVlDQogICAgICAgIGVuZA0KICAgIGVuZA0KICAgIHJldHVybiBmYWxzZQ0KZW5kDQoNCmxvY2FsIGZ1bmN0aW9uIGNoZWNrRnVuY3Rpb25zKCkNCiAgICBmb3IgbmFtZSwgaW5mbyBpbiBwYWlycyhwcm90ZWN0ZWRGdW5jdGlvbnMpIGRvDQogICAgICAgIGxvY2FsIGN1cnJlbnRTaWcgPSBmdW5jdGlvblNpZ25hdHVyZShpbmZvLnJlZikNCiAgICAgICAgaWYgY3VycmVudFNpZyB+PSBpbmZvLnNpZ25hdHVyZSB0aGVuDQogICAgICAgICAgICB0cmlnZ2VyVGFtcGVyKA==')Protected function changed: GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('FpXWSHWaTQsotqOLYbpPChdCubztzjSuAnOtGxggIbtqZfjYairCAFLIC4uIHRvc3RyaW5nKG5hbWUpIC4uIA==') original:GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('qTBSQIjFUeLxwZeJAidsrhojblACVjtcbYNUklHMbupNzyvlXRIMggkIC4uIHRvc3RyaW5nKGluZm8uc2lnbmF0dXJlKSAuLiA=') current:GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('dtIgNijayfTFsIsSxRrMQuMAHeBGdyVIPibLoMQcldRUDAajVjZEEGyIC4uIHRvc3RyaW5nKGN1cnJlbnRTaWcpKQ0KICAgICAgICAgICAgcmV0dXJuIHRydWUNCiAgICAgICAgZW5kDQogICAgZW5kDQogICAgcmV0dXJuIGZhbHNlDQplbmQNCg0KbG9jYWwgZnVuY3Rpb24gY2hlY2tSZW1vdGVIb29rcygpDQogICAgLS0gYmVzdC1lZmZvcnQ6IGlmIFJlbW90ZUd1YXJkIHByb3ZpZGVzIGEgbGlzdCBvZiBibG9ja2VkIHJlbW90ZXMgYW5kIHRoZWlyIG9yaWdpbmFsIGhvb2tzLA0KICAgIC0tIHZlcmlmeSB0aGF0IHRob3NlIHJlZmVyZW5jZXMgc3RpbGwgZXhpc3QgKGZ1bmN0aW9uIGlkZW50aXR5KSBhbmQgYXJlIGNhbGxhYmxlDQogICAgaWYgVGFtcGVyUHJvdGVjdGlvbi5SZW1vdGVHdWFyZCBhbmQgVGFtcGVyUHJvdGVjdGlvbi5SZW1vdGVHdWFyZC5CbG9ja2VkUmVtb3RlcyB0aGVuDQogICAgICAgIGZvciByZW1vdGUsIG9yaWdpbmFsIGluIHBhaXJzKFRhbXBlclByb3RlY3Rpb24uUmVtb3RlR3VhcmQuQmxvY2tlZFJlbW90ZXMpIGRvDQogICAgICAgICAgICBpZiBub3QgcmVtb3RlIG9yIG5vdCByZW1vdGUuUGFyZW50IHRoZW4NCiAgICAgICAgICAgICAgICB0cmlnZ2VyVGFtcGVyKA==')Remote missing or destroyed while protected: GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('bLznzLIXzPfVWRvfhoVVwjDuSZutIVgHJvrQxuWAqlFmVeAorzWocubIC4uIHRvc3RyaW5nKHJlbW90ZSkgKQ0KICAgICAgICAgICAgICAgIHJldHVybiB0cnVlDQogICAgICAgICAgICBlbmQNCiAgICAgICAgICAgIC0tIGNoZWNrIHRoYXQgRmlyZVNlcnZlciBzdGlsbCBwb2ludHMgdG8gYSBob29rIGJ5IGNvbXBhcmluZyB0b3N0cmluZyBvciBkZWJ1Zy5nZXRpbmZvDQogICAgICAgICAgICBsb2NhbCBvaywgaW5mbyA9IHBjYWxsKGZ1bmN0aW9uKCkNCiAgICAgICAgICAgICAgICBpZiB0eXBlKHJlbW90ZS5GaXJlU2VydmVyKSA9PSA=')functionGpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('vcOfDFozXWgSVMsSzLnMtVmwwGXqogSZabQyNzKOztUXEVdRePnviimIHRoZW4NCiAgICAgICAgICAgICAgICAgICAgLS0gaWYgdGhlIG9yaWdpbmFsIHN0b3JlZCA=')originalGpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('iLROEZFwUDkJMTviKBSDTOyiJTStsfNYsuwZJQboVCDbXLmwSkkVDneIGlzIGEgZnVuY3Rpb24sIGNvbXBhcmUgdG9zdHJpbmcNCiAgICAgICAgICAgICAgICAgICAgaWYgb3JpZ2luYWwgYW5kIHRvc3RyaW5nKG9yaWdpbmFsKSB+PSB0b3N0cmluZyhyZW1vdGUuRmlyZVNlcnZlcikgdGhlbg0KICAgICAgICAgICAgICAgICAgICAgICAgLS0gcG9zc2libGUgb3ZlcndyaXRlDQogICAgICAgICAgICAgICAgICAgICAgICB0cmlnZ2VyVGFtcGVyKA==')Remote.FireServer seems overwritten: GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('KDmCBiecwwpKVXwgmnXVypQMdjVSDRURPLkARJiiliFXkiQYnGauHrNIC4uIHRvc3RyaW5nKHJlbW90ZS5OYW1lKSkNCiAgICAgICAgICAgICAgICAgICAgICAgIHJldHVybiB0cnVlDQogICAgICAgICAgICAgICAgICAgIGVuZA0KICAgICAgICAgICAgICAgIGVuZA0KICAgICAgICAgICAgZW5kKQ0KICAgICAgICAgICAgaWYgb2sgYW5kIGluZm8gdGhlbg0KICAgICAgICAgICAgICAgIHJldHVybiB0cnVlDQogICAgICAgICAgICBlbmQNCiAgICAgICAgZW5kDQogICAgZW5kDQogICAgcmV0dXJuIGZhbHNlDQplbmQNCg0KbG9jYWwgZnVuY3Rpb24gcnVuSW50ZWdyaXR5Q2hlY2tzKCkNCiAgICAtLSBydW5zIGEgc2V0IG9mIGNoZWNrczsgcmV0dXJucyB0cnVlIGlmIHRhbXBlciB0cmlnZ2VyZWQNCiAgICBpZiBjaGVja0luc3RhbmNlcygpIHRoZW4gcmV0dXJuIHRydWUgZW5kDQogICAgaWYgY2hlY2tGdW5jdGlvbnMoKSB0aGVuIHJldHVybiB0cnVlIGVuZA0KICAgIGlmIGNoZWNrUmVtb3RlSG9va3MoKSB0aGVuIHJldHVybiB0cnVlIGVuZA0KICAgIHJldHVybiBmYWxzZQ0KZW5kDQoNCi0tIFB1YmxpYyBBUEkgLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tDQpmdW5jdGlvbiBUYW1wZXJQcm90ZWN0aW9uOlByb3RlY3RJbnN0YW5jZShuYW1lLCBpbnN0YW5jZSkNCiAgICBpZiBub3QgbmFtZSBvciBub3QgaW5zdGFuY2UgdGhlbiByZXR1cm4gZmFsc2UgZW5kDQogICAgcHJvdGVjdGVkSW5zdGFuY2VzW25hbWVdID0gaW5zdGFuY2UNCiAgICBsb2co')Protecting instance: GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('ltWpYKpvHExHZOdQfaiIfxHIrCYFCwHjOjLfhTQzBUBCbGyixUiigLEIC4uIHRvc3RyaW5nKG5hbWUpIC4uIA==') -> GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('sgtRoXPkfdWlWYPMiFlowdhjIBztOhUbMrZjHYUdAQNeSOrJjMClhhAIC4uIGdldEluc3RhbmNlUGF0aChpbnN0YW5jZSkpDQogICAgcmV0dXJuIHRydWUNCmVuZA0KDQpmdW5jdGlvbiBUYW1wZXJQcm90ZWN0aW9uOlByb3RlY3RGdW5jdGlvbihuYW1lLCBmbikNCiAgICBpZiBub3QgbmFtZSBvciB0eXBlKGZuKSB+PSA=')functionGpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('MOLotUsKsNubSfglGhfxLBxGOamBUmMILmxQeepgtTmbQEcgLSSpsCKIHRoZW4gcmV0dXJuIGZhbHNlIGVuZA0KICAgIHByb3RlY3RlZEZ1bmN0aW9uc1tuYW1lXSA9IHsgcmVmID0gZm4sIHNpZ25hdHVyZSA9IGZ1bmN0aW9uU2lnbmF0dXJlKGZuKSB9DQogICAgbG9nKA==')Protecting function: GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('xzqzcCnJtlCaXLZeYgiMEMalcxOpquIYPZGBdbJjnANkEhSxrlxrdCvIC4uIHRvc3RyaW5nKG5hbWUpIC4uIA==') sig:GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('xccynNZiVXwfhLLEkZojxWNZxyrPLqNyZBMULOSnZZgRHZMTAONfEDPIC4uIHRvc3RyaW5nKHByb3RlY3RlZEZ1bmN0aW9uc1tuYW1lXS5zaWduYXR1cmUpKQ0KICAgIHJldHVybiB0cnVlDQplbmQNCg0KZnVuY3Rpb24gVGFtcGVyUHJvdGVjdGlvbjpTdGFydChvcHRzKQ0KICAgIGlmIHJ1bm5pbmcgdGhlbiByZXR1cm4gZW5kDQogICAgb3B0cyA9IG9wdHMgb3Ige30NCiAgICBmb3Igayx2IGluIHBhaXJzKG9wdHMpIGRvIGNvbmZpZ1trXSA9IHYgZW5kDQoNCiAgICAtLSBsaW5rIG9wdGlvbmFsIG1vZHVsZXMgZnJvbSBvcHRzIHRhYmxlDQogICAgaWYgb3B0cy5Mb2dnZXIgdGhlbiBUYW1wZXJQcm90ZWN0aW9uLkxvZ2dlciA9IG9wdHMuTG9nZ2VyIGVuZA0KICAgIGlmIG9wdHMuR1VJTWFuYWdlciB0aGVuIFRhbXBlclByb3RlY3Rpb24uR1VJTWFuYWdlciA9IG9wdHMuR1VJTWFuYWdlciBlbmQNCiAgICBpZiBvcHRzLlJlbW90ZUd1YXJkIHRoZW4gVGFtcGVyUHJvdGVjdGlvbi5SZW1vdGVHdWFyZCA9IG9wdHMuUmVtb3RlR3VhcmQgZW5kDQogICAgaWYgb3B0cy5JbnZlbnRvcnlMb2NrIHRoZW4gVGFtcGVyUHJvdGVjdGlvbi5JbnZlbnRvcnlMb2NrID0gb3B0cy5JbnZlbnRvcnlMb2NrIGVuZA0KDQogICAgLS0gZGVmYXVsdCBwcm90ZWN0IEdVSSBpZiBwYXNzZWQNCiAgICBpZiBUYW1wZXJQcm90ZWN0aW9uLkdVSU1hbmFnZXIgYW5kIFRhbXBlclByb3RlY3Rpb24uR1VJTWFuYWdlci5TY3JlZW5HdWkgdGhlbg0KICAgICAgICBzZWxmOlByb3RlY3RJbnN0YW5jZSg=')ScreenGuiGpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('bPEJInefbDxrEyUcvOSktdsfIgLSKToEZiDRpJcsVFeRTMYVzxQvNhmLCBUYW1wZXJQcm90ZWN0aW9uLkdVSU1hbmFnZXIuU2NyZWVuR3VpKQ0KICAgIGVuZA0KICAgIGlmIFRhbXBlclByb3RlY3Rpb24uR1VJTWFuYWdlciBhbmQgVGFtcGVyUHJvdGVjdGlvbi5HVUlNYW5hZ2VyLlN0YXR1c0RvdCB0aGVuDQogICAgICAgIHNlbGY6UHJvdGVjdEluc3RhbmNlKA==')StatusDotGpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('PBTnHaSTHRPQXfGrABtPWkPTbcyiPXzjpCcLbkuldCTLqPPbLDJideGLCBUYW1wZXJQcm90ZWN0aW9uLkdVSU1hbmFnZXIuU3RhdHVzRG90KQ0KICAgIGVuZA0KDQogICAgLS0gYXR0ZW1wdCB0byBwcm90ZWN0IHNvbWUgYnVpbHQtaW4gZnVuY3Rpb25zIGlmIGF2YWlsYWJsZQ0KICAgIGlmIHR5cGUoaG9va2Z1bmN0aW9uKSA9PSA=')functionGpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('GwDpqyhpBlamRZkwCaapXfJResDLrszGbSzUfMyNrORqktxRKRQUZmfIHRoZW4NCiAgICAgICAgc2VsZjpQcm90ZWN0RnVuY3Rpb24o')hookfunctionGpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('jplxJiAoiGMjlgdQWJmHrRbCnXihqQzVGsoxtQOXEYmvGgijWRAMzJtLCBob29rZnVuY3Rpb24pDQogICAgZW5kDQogICAgaWYgZGVidWcgYW5kIHR5cGUoZGVidWcuZ2V0aW5mbykgPT0g')functionGpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('RqryiHNWaSOkFYPsFJTNCaJvXCbfUmIhCZQinQBwBWEckHAiZyrTimDIHRoZW4NCiAgICAgICAgc2VsZjpQcm90ZWN0RnVuY3Rpb24o')debug.getinfoGpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('WmctcJqOpCMctikIKWcTEjjXLwyrklNFMxBVRPBdHFzXMHJwgbYzkNoLCBkZWJ1Zy5nZXRpbmZvKQ0KICAgIGVuZA0KDQogICAgcnVubmluZyA9IHRydWUNCiAgICBsb2co')TamperProtection started. Interval=GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('RvjWHVTPVewobqyKzCRQMCVUKuZKmEvSQqakxKaCqioaUxgZvqYAOyuLi50b3N0cmluZyhjb25maWcuQ2hlY2tJbnRlcnZhbCkpDQoNCiAgICAtLSBzdGFydCBwZXJpb2RpYyBpbnRlZ3JpdHkgbG9vcA0KICAgIHNwYXduKGZ1bmN0aW9uKCkNCiAgICAgICAgd2hpbGUgcnVubmluZyBkbw0KICAgICAgICAgICAgbG9jYWwgb2sgPSBwY2FsbChydW5JbnRlZ3JpdHlDaGVja3MpDQogICAgICAgICAgICAtLSBpZiBhIHRhbXBlciB3YXMgdHJpZ2dlcmVkIGluc2lkZSBjaGVja3MsIHJ1bkludGVncml0eUNoZWNrcyB3aWxsIGNhbGwgdHJpZ2dlclRhbXBlciBhbmQgbWF5IGtpY2sNCiAgICAgICAgICAgIC0tIHNvIHdlIGRvbg==')t need to handle it here besides sleeping
            task.wait(config.CheckInterval)
        end
    end)
end

function TamperProtection:Stop()
    running = false
    log(GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('CarxELukrXZqYxBLWjpQfrRLUtsYzexyzuRDntJVAreyPngwupFErlqVGFtcGVyUHJvdGVjdGlvbiBzdG9wcGVkLg=='))
end

-- Lightweight self-heal: re-protect instances by cloning if possible
function TamperProtection:AttemptRestore()
    if not TamperProtection.GUIManager or not TamperProtection.GUIManager.ScreenGui then return end
    local sg = TamperProtection.GUIManager.ScreenGui
    if not sg.Parent then
        local cloneOk, clone = pcall(function() return sg:Clone() end)
        if cloneOk and clone then
            pcall(function() clone.Parent = LocalPlayer:FindFirstChild(GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('nTlrIWhFGbgjBNzHlgzHpwBiqWjsGmpnDlouHuiqEHcPyUsYZGfwmdEUGxheWVyR3Vp')) or LocalPlayer end)
            TamperProtection.GUIManager.ScreenGui = clone
            self:ProtectInstance(GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('gNgBvsOuBvAkRPYksizHtPfGjkBjqDlwuSbjlXrhzVjkzCtyznuKTdhU2NyZWVuR3Vp'), clone)
            log(GpNjJASOXxdeahngcDtobvqNTsilcdOFTOvtiJBDSXvdwURKPTrMXFXxdDxinjdFTgtetXyHLRGMO('PNzTXJRKuBdKWtPcXNDjYDjZBdnrmkXfohaiyVqysaFxOlPMaiTPXWOU2NyZWVuR3VpIHJlc3RvcmVkIHZpYSBjbG9uZS4='))
        end
    end
end

-- Expose module
return TamperProtection
    
